### ISSUE TITLE
Compile failure: Could not find io.micronaut.graphql:micronaut-graphql-gorm:1.1.0.BUILD-SNAPSHOT

### ISSUE THREAD

**Issue by djaysrc** [jameskleeh/micronaut-gorm-graphql-example#1]
Execution failed for task ':compileGroovy'.
> Could not resolve all files for configuration ':compileClasspath'.
   > Could not find io.micronaut.graphql:micronaut-graphql-gorm:1.1.0.BUILD-SNAPSHOT.

@jameskleeh Where is this snapshot artifact? Is it built from another project? If yes, Which one?

**Comment by djaysrc** [comment]
> Execution failed for task ':compileGroovy'.
> 
> > Could not resolve all files for configuration ':compileClasspath'.
> > Could not find io.micronaut.graphql:micronaut-graphql-gorm:1.1.0.BUILD-SNAPSHOT.
> 
> @jameskleeh Where is this snapshot artifact? Is it built from another project? If yes, Which one?

Nevermind,
Found it...
https://oss.sonatype.org/content/repositories/snapshots/io/micronaut/graphql/micronaut-graphql-gorm/1.1.0.BUILD-SNAPSHOT/

**Comment by jameskleeh** [comment]
@djaysrc You can just use `1.1.0`. This sample was created before 1.1 was released
