### ISSUE TITLE
org.hibernate.Criteria API is deprecated

### ISSUE THREAD

**Issue by djaysrc** [jameskleeh/micronaut-gorm-graphql-example#2]
> 13:40:31.575 [nioEventLoopGroup-1-2] WARN  org.hibernate.orm.deprecation - HHH90000022: Hibernate's legacy org.hibernate.Criteria API is deprecated; use the JPA javax.persistence.criteria.CriteriaQuery instead

What changes need to be made avoid this deprecation warning? Assuming this is in GORM? Pointers to fix this?

**Comment by jameskleeh** [comment]
@djaysrc The changes would need to be made in these classes https://github.com/grails/gorm-graphql/tree/master/core/src/main/groovy/org/grails/gorm/graphql/fetcher/impl. Unfortunately Hibernate decided to deprecate criteria without providing all of the functionality through other means. That is why GORM hasn't switched over yet. https://github.com/grails/grails-data-mapping/issues/941

**Comment by anu-devco** [comment]
Apologies for bumping up on this issue this late but...

Is this ever going to be fixed or should we move away from GORM in Micronaut? 
I have a whole application written utilising GORM back in 2018.
I just updated it to Micronaut 2.4.2 thinking we would have any updated implementation of GORM in Micronaut by now.

FYI I am using GORM Finders and Criteria and both seem to be giving warning.
